
- name: OS level tasks
  hosts: minikube
  connection: local
  vars:
    ansible_user: 'root'
  roles:
  - { name: roles/minikube_as_root }

- name: Minikube
  hosts: minikube
  connection: local
  vars:
    ansible_user: '{{ minikube_user }}'
  roles:
  - { name: roles/minikube_as_user }
  - { name: roles/awx }
